# Optional: Default active environment if hostname detection fails
active_environment: "local_directories"

local_directories:
  ECLARE_ROOT: "/path/to/ECLARE"
  OUTPATH: "/path/to/outputs"
  DATAPATH: "/path/to/data"
  NAMPATH: "/path/to/neural-additive-models-pt"