# Hostname to environment mapping
hostname_mapping:
  "MacBook-Pro-de-Dylan.local": "local_directories"                               # Exact hostname match
  "/^narval-.*/": "narval_directories"                                            # Regex pattern for Narval hosts
  "/(mcb|buckeridge|hlr-cfi|ri-muhc|wh|yl)/": "mcb_directories"                   # Regex pattern for MCB hosts

# Optional: Default active environment if hostname detection fails
active_environment: "local_directories"

# Environment-specific directories
local_directories:
  ECLARE_root: "/Users/dmannk/cisformer/ECLARE"
  outpath: "/Users/dmannk/cisformer/outputs"
  datapath: "/Users/dmannk/cisformer/data"

narval_directories:
  ECLARE_root: "/home/dmannk/projects/def-liyue/dmannk/CLARE"
  outpath: "/home/dmannk/scratch"
  datapath: "/home/dmannk/projects/def-liyue/dmannk/data"

mcb_directories:
  ECLARE_root: "/home/mcb/users/dmannk/scMultiCLIP/CLARE"
  outpath: "/home/mcb/users/dmannk/scMultiCLIP/outputs"
  datapath: "/home/mcb/users/dmannk/scMultiCLIP/data"
