name: nam-pt
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=20.0.2
  - cudatoolkit=11.0
  - pip:
    - torch==1.7.0
    - fsspec==0.8.4
    - pandas==1.1.4
    - tqdm==4.54.0
    - sklearn==0.0
    - absl-py==0.11.0
    - gcsfs==0.7.1
